export const FETCH_PHOTOS_REQUEST = 'ROVER_PHOTOS/FETCH_PHOTOS_REQUEST';
export const FETCH_PHOTOS_SUCCESS = 'ROVER_PHOTOS/FETCH_PHOTOS_SUCCESS';
export const FETCH_PHOTOS_FAILURE = 'ROVER_PHOTOS/FETCH_PHOTOS_FAILURE';
export const CHANGE_SOL = 'ROVER_PHOTOS/CHANGE_SOL';
